###

POST http://localhost:4040/register
Content-Type: application/json

{
  "username": "quocgia",
  "password": "admin"  
}

###

POST http://localhost:4040/login
Content-Type: application/json

{
  "username": "quocgia",
  "password": "admin"
}